// 北京欢乐谷 out of the cached OSM data and into src/park/Osm.ts: the park outline, its lakes and
// every attraction OSM knows the name of, in park-local metres (+X east, +Z south) about the
// outline's bounding-box centre. Re-run after scripts/city/fetch-osm.mjs.
//   node scripts/park/extract.mjs
import fs from 'node:fs';
import path from 'node:path';
import { project } from '../city/region.mjs';

const PARK_WAY = 29171402;
const root = path.resolve(import.meta.dirname, '../..');
const dir = path.join(root, '.cache/osm');
const els = new Map();
for (const f of fs.readdirSync(dir).filter((f) => f.endsWith('.json'))) {
  for (const e of JSON.parse(fs.readFileSync(path.join(dir, f), 'utf8')).elements) els.set(e.type[0] + e.id, e);
}
const park = els.get('w' + PARK_WAY);
if (!park) throw new Error('park way not in the OSM cache - run scripts/city/fetch-osm.mjs first');

const outline = park.geometry.map((g) => project(g.lat, g.lon));
const xs = outline.map((p) => p[0]), zs = outline.map((p) => p[1]);
const cx = (Math.min(...xs) + Math.max(...xs)) / 2, cz = (Math.min(...zs) + Math.max(...zs)) / 2;
const KZ = (Math.PI / 180) * 6378137, KX = KZ * Math.cos(39.90883 * Math.PI / 180);
const lat = 39.90883 - cz / KZ, lon = 116.39757 + cx / KX;
const q = (v) => Math.round(v * 10) / 10;
const local = (p) => [q(p[0] - cx), q(p[1] - cz)];
const fmt = (pts) => '[' + pts.map(([x, z]) => `[${x}, ${z}]`).join(', ') + ']';

const inside = (x, z) => {
  let hit = false;
  for (let i = 0, j = outline.length - 1; i < outline.length; j = i++) {
    const [xi, zi] = outline[i], [xj, zj] = outline[j];
    if ((zi > z) !== (zj > z) && x < ((xj - xi) * (z - zi)) / (zj - zi) + xi) hit = !hit;
  }
  return hit;
};
const centroid = (e) => {
  if (e.type === 'node') return project(e.lat, e.lon);
  const p = e.geometry.filter(Boolean).map((g) => project(g.lat, g.lon));
  return [p.reduce((a, v) => a + v[0], 0) / p.length, p.reduce((a, v) => a + v[1], 0) / p.length];
};

// Lakes: closed water ways inside the park (the open ones are the streams that join them).
const water = [];
for (const e of els.values()) {
  const t = e.tags || {};
  if (!e.geometry || !(t.natural === 'water' || t.water)) continue;
  const [x, z] = centroid(e);
  if (!inside(x, z)) continue;
  const pts = e.geometry.map((g) => project(g.lat, g.lon));
  const a = pts[0], b = pts[pts.length - 1];
  if (Math.hypot(a[0] - b[0], a[1] - b[1]) > 5 || pts.length < 8) continue;
  water.push({ id: e.id, pts: pts.slice(0, -1).map(local) });
}
water.sort((a, b) => a.id - b.id);

// The park's own circulation: OSM footways and service roads inside the boundary.
const paths = [];
for (const e of els.values()) {
  const t = e.tags || {};
  if (!e.geometry || !t.highway) continue;
  if (!/^(footway|path|pedestrian|service|cycleway|steps)$/.test(t.highway)) continue;
  const keep = e.geometry.map((g) => project(g.lat, g.lon)).filter(([x, z]) => inside(x, z));
  if (keep.length < 2) continue;
  const wide = t.highway === 'pedestrian' || t.highway === 'service';
  paths.push({ id: e.id, w: wide ? 6 : 3.2, pts: keep.map(local) });
}
paths.sort((a, b) => a.id - b.id);

const attractions = [];
for (const e of els.values()) {
  const t = e.tags || {};
  if (e.id === PARK_WAY || !t.name) continue;
  if (!(t.tourism === 'attraction' || t.tourism === 'aquarium' || t.attraction)) continue;
  if (!(e.geometry || e.lat !== undefined)) continue;
  const [x, z] = centroid(e);
  if (!inside(x, z)) continue;
  const [lx, lz] = local([x, z]);
  attractions.push({ name: t.name, x: lx, z: lz });
}
attractions.sort((a, b) => a.name.localeCompare(b.name, 'zh'));

const out = `// GENERATED by scripts/park/extract.mjs from the OSM cache - do not edit by hand.
// 北京欢乐谷 (OSM way ${PARK_WAY}, tourism=theme_park) in park-local metres: +X east, +Z south,
// origin at the centre of the park's bounding box. Data © OpenStreetMap contributors, ODbL.

/** WGS84 of the local origin. */
export const PARK_CENTRE = { lat: ${lat.toFixed(6)}, lon: ${lon.toFixed(6)} };

export type Poly = [number, number][];

/** The park boundary, ${outline.length - 1} points, ${q(Math.max(...xs) - Math.min(...xs))} x ${q(Math.max(...zs) - Math.min(...zs))} m. */
export const OUTLINE: Poly = ${fmt(outline.slice(0, -1).map(local))};

/** The park's lakes (closed water ways only; the streams that link them are left out). */
export const WATER: Poly[] = [
${water.map((w) => `  ${fmt(w.pts)},`).join('\n')}
];

/** The park's own footways and service roads, as polylines with a width in metres. */
export const PATHS: { w: number; pts: Poly }[] = [
${paths.map((p) => `  { w: ${p.w}, pts: ${fmt(p.pts)} },`).join('\n')}
];

/** Every attraction OSM has a name for, as a label point. */
export const ATTRACTIONS: { name: string; x: number; z: number }[] = [
${attractions.map((a) => `  { name: '${a.name}', x: ${a.x}, z: ${a.z} },`).join('\n')}
];

/** Named point of an attraction, or null. */
export function at(name: string): { x: number; z: number } | null {
  const a = ATTRACTIONS.find((v) => v.name === name);
  return a ? { x: a.x, z: a.z } : null;
}
`;
fs.writeFileSync(path.join(root, 'src/park/Osm.ts'), out);
console.log(`src/park/Osm.ts: outline ${outline.length - 1} pts, ${water.length} lakes, ${paths.length} paths, ${attractions.length} attractions`);
console.log(`centre ${lat.toFixed(6)}, ${lon.toFixed(6)}  world ${cx.toFixed(1)}, ${cz.toFixed(1)}`);
